# Generated by Django 4.2.3 on 2026-09-29 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0005_section'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='问题标题')),
                ('content', models.TextField(blank=True, max_length=256, null=True, verbose_name='问题内容')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('answers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='question_app.question_app', verbose_name='回答')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.section', verbose_name='章节')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_app', to='user.user', verbose_name='提问者')),
            ],
            options={
                'db_table': 't_question_app',
            },
        ),
    ]
