# Generated by Django 4.2.3 on 2026-09-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_section'),
        ('question_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_app',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_app', to='course_app.section', verbose_name='章节'),
        ),
    ]
