# Generated by Django 4.2.3 on 2026-09-30 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0005_section'),
        ('plan_app', '0002_classtype'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_app',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('order_type', models.IntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='订单状态')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='订单金额')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际订单金额')),
                ('gemt_payment', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('classtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_app', to='plan_app.classtype', verbose_name='分配的班级')),
                ('coursr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_app', to='course_app.course', verbose_name='下单的课程')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_app', to='user.user', verbose_name='订单用户')),
            ],
            options={
                'db_table': 't_order_app',
            },
        ),
    ]
