# Generated by Django 4.2.3 on 2026-09-28 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0005_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='计划名称')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='计划介绍')),
                ('info', models.TextField(blank=True, null=True, verbose_name='计划信息')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='course_app.course', verbose_name='课程')),
            ],
            options={
                'db_table': 't_plan',
            },
        ),
    ]
