# Generated by Django 4.2.3 on 2026-09-28 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_section'),
        ('plan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('all_stage', models.IntegerField(blank=True, default=1, null=True, verbose_name='所有阶段')),
                ('supervision', models.IntegerField(blank=True, default=1, null=True, verbose_name='督导')),
                ('update', models.IntegerField(blank=True, default=1, null=True, verbose_name='update service')),
                ('homework', models.IntegerField(blank=True, default=1, null=True, verbose_name='作业')),
                ('online', models.IntegerField(blank=True, default=1, null=True, verbose_name='线上')),
                ('work', models.IntegerField(blank=True, default=1, null=True, verbose_name='work in join')),
                ('remote', models.IntegerField(blank=True, default=1, null=True, verbose_name='远程')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_type', to='course_app.course', verbose_name='课程')),
            ],
            options={
                'db_table': 't_class_type',
            },
        ),
    ]
