# Generated by Django 4.2.3 on 2026-09-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RotationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='轮播名称')),
                ('img', models.CharField(max_length=256, verbose_name='轮播图片')),
            ],
            options={
                'db_table': 't_rotation_chart',
            },
        ),
    ]
