# Generated by Django 4.2.3 on 2026-09-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='特色服务名称')),
            ],
            options={
                'db_table': 't_feature_service',
            },
        ),
    ]
