# Generated by Django 4.2.3 on 2026-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='教师姓名')),
                ('brief', models.CharField(blank=True, max_length=256, null=True, verbose_name='教师简介')),
                ('avatr', models.CharField(blank=True, max_length=256, null=True, verbose_name='教师头像')),
                ('position', models.CharField(blank=True, max_length=256, null=True, verbose_name='教师职位')),
            ],
            options={
                'db_table': 't_teacher',
            },
        ),
    ]
