# Generated by Django 4.2.3 on 2026-09-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='characteristic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='教师特点'),
        ),
    ]
