# Generated by Django 4.2.3 on 2026-09-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_teacher_characteristic'),
        ('course_app', '0005_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='课程价格')),
                ('img', models.CharField(blank=True, max_length=256, null=True, verbose_name='课程图片')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='结束时间')),
                ('stage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freecourse', to='course_app.stage', verbose_name='课程阶段')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freecourse', to='teachers.teacher', verbose_name='课程讲师')),
            ],
            options={
                'db_table': 't_freecourese',
            },
        ),
    ]
