# Generated by Django 4.2.3 on 2026-09-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freecourse',
            old_name='stage_id',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='freecourse',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
