"""
Django settings for jiaoyu_env project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
# 获取项目根目录
DASE_DIR=Path(__file__).resolve().parent.parent
# 加载env文件
load_dotenv(DASE_DIR /'.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# 配置是否允许外网访问
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "user",
    "course_app",
    "django_filters",
    "teachers",
    "free_course_app",
    "homepage_app",
    "plan_app",
    "updata_app",
    "preson_app",
    "question_app",
    "order_app"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 配置中间件
    # "user.middleware.LoginMiddleware"
]

ROOT_URLCONF = 'jiaoyu_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jiaoyu_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
# 配置上传文件的根目录
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
# 上传文件的地址
MEDIA_URL="/media/"

# 设置过期时间
JWT_EXPIRATION_DELTA=60*60*60*7



#配置jwt验证 
REST_FRAMEWORK = {
    
    "DEFAULT_AUTHENTICATION_CLASSES": [
        ## user是需要验证的子应用名称 文件名称 类名
        "user.authentication.JWTAuthentication",

    ],
    # 配置过滤器 视图过滤器
     'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
  # 设置登录视图限流
      'DEFAULT_THROTTLE_CLASSES': (
    'rest_framework.throttling.ScopedRateThrottle',
   ),
  'DEFAULT_THROTTLE_RATES': {
    'login': '10/day'
   }

}

# 设置分页页数
# PAGE_SIZE=10

# 配置redis缓存
CACHES = {
  # default 是缓存名，可以配置多个缓存
  "default": {
    #  RedisCache 缓存类,将缓存数据存放到哪里 redis缓存类
    "BACKEND": "django.core.cache.backends.redis.RedisCache",
    # 配置正确的 ip和port
    "LOCATION": "redis://127.0.0.1:6379",
    #缓存间隔时间
    "TIMEOUT":300,
    # 额外参数
    "OPTIONS": {
        # 用redis中那个数据库
      'db': '9',
    #   链接池 提升性能
      'parser_class': 'redis.connection.PythonParser',
      'pool_class': 'redis.BlockingConnectionPool',
      # 如果 redis 设置了密码，那么这里需要设置对应的密码，如果redis没有设置密码，那么这里也不设置
      # "PASSWORD": "123456",
     }
   }
}


