# Generated by Django 4.2.3 on 2026-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='supervision',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='课程监督方式'),
        ),
    ]
