# Generated by Django 4.2.3 on 2026-09-20 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_course_supervision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='课程阶段名称')),
                ('introduction', models.CharField(blank=True, max_length=256, null=True, verbose_name='课程阶段介绍')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='课程阶段级别')),
                ('is_free', models.IntegerField(blank=True, null=True, verbose_name='是否免费')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='course_app.course', verbose_name='课程分类')),
            ],
            options={
                'db_table': 't_stage',
            },
        ),
    ]
