# Generated by Django 4.2.3 on 2026-09-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='课程章节的名称')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='课程章节的级别')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='course_app.stage', verbose_name='课程阶段')),
            ],
            options={
                'db_table': 't_chapter',
            },
        ),
    ]
