# Generated by Django 4.2.3 on 2026-09-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='课程小结名称')),
                ('is_must', models.IntegerField(blank=True, null=True, verbose_name='是否必修')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='课程时长')),
                ('learned_count', models.IntegerField(blank=True, null=True, verbose_name='学习人数')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='课程小节视频地址')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sction', to='course_app.chapter', verbose_name='课程章节')),
            ],
            options={
                'db_table': 't_section',
            },
        ),
    ]
