# Generated by Django 4.2.3 on 2026-09-19 08:31

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='用户名称')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='手机号')),
                ('pwd', models.CharField(max_length=256, verbose_name='密码')),
                ('size', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=256, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('job_title', models.CharField(max_length=256, null=True, verbose_name='职位')),
                ('introduction', models.CharField(blank=True, max_length=256, null=True, verbose_name='简介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user.models.get_imge)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户模型',
                'db_table': 't_user',
            },
        ),
    ]
