# Generated by Django 4.2.3 on 2026-09-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('course_app', '0005_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='preson_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course_app.course', verbose_name='课程内容')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user', verbose_name='用户名称')),
            ],
            options={
                'db_table': 't_user_course',
            },
        ),
    ]
