# Generated by Django 4.2.3 on 2026-09-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('course_app', '0005_section'),
        ('preson_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preson_app',
            name='name',
        ),
        migrations.AddField(
            model_name='preson_app',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preson_app', to='user.user', verbose_name='用户名称'),
        ),
        migrations.AlterField(
            model_name='preson_app',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preson_app', to='course_app.course', verbose_name='课程内容'),
        ),
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_section', to='course_app.section', verbose_name='课程小节')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_section', to='user.user', verbose_name='用户名称')),
            ],
            options={
                'db_table': 't_user_section',
            },
        ),
    ]
