
insert into t_stage (name,introduction,course_id,level) values ('JAVA 快速入门','Java快速入门',1,1);
insert into t_stage (name,introduction,course_id,level) values ('JAVA 基础深化和提高','Java基础深化和提高',1,2);
insert into t_stage (name,introduction,course_id,level) values ('数据库编程','数据库编程',1,3);
insert into t_stage (name,introduction,course_id,level) values ('网页编程和设计','网页编程和设计',1,4);
insert into t_stage (name,introduction,course_id,level) values ('JavaWeb开发','JavaWeb开发',1,5);
insert into t_stage (name,introduction,course_id,level) values ('项目管理与SSM框架','项目管理与SSM框架',1,6);
insert into t_stage (name,introduction,course_id,level) values ('生产环境部署与协同开发','生产环境部署与协同开发',1,7);
insert into t_stage (name,introduction,course_id,level) VALUES ('SpringBoot与MybatisPlus','SpringBoot与MybatisPlus',1,8);
insert into t_stage (name,introduction,course_id,level) VALUES ('权限控制与安全认证','权限控制与安全认证',1,9);
insert into t_stage (name,introduction,course_id,level) VALUES ('百战旅游网项目','百战旅游网项目',1,10);
insert into t_stage (name,introduction,course_id,level) VALUES ('高性能消息中间件','高性能消息中间件',1,11);
insert into t_stage (name,introduction,course_id,level) VALUES ('分布式调用与高并发处理','分布式调用与高并发处理',1,12);
insert into t_stage (name,introduction,course_id,level) VALUES ('分布式文件存储与数据缓存','分布式文件存储与数据缓存',1,13);
insert into t_stage (name,introduction,course_id,level) VALUES ('海量数据存储与查询','海量数据存储与查询',1,14);
insert into t_stage (name,introduction,course_id,level) VALUES ('全文检索与日志管理','全文检索与日志管理',1,15);
insert into t_stage (name,introduction,course_id,level) VALUES ('前后端分离技术VUE','前后端分离技术VUE',1,16);
insert into t_stage (name,introduction,course_id,level) VALUES ('微信与支付宝在线支付','微信与支付宝在线支付',1,17);
insert into t_stage (name,introduction,course_id,level) VALUES ('亿级高并发电商项目','亿级高并发电商项目',1,18);
insert into t_stage (name,introduction,course_id,level) VALUES ('Spring Cloud微服务技术栈','Spring Cloud微服务技术栈',1,19);
insert into t_stage (name,introduction,course_id,level) VALUES ('租房网(Spring Cloud最新架构)','租房网(Spring Cloud最新架构)',1,20);
insert into t_stage (name,introduction,course_id,level) VALUES ('Spring Cloud Alibaba技术栈','Spring Cloud Alibaba技术栈',1,21);
insert into t_stage (name,introduction,course_id,level) VALUES ('分布式医疗云平台','分布式医疗云平台',1,22);
insert into t_stage (name,introduction,course_id,level) VALUES ('容器管理技术','容器管理技术',1,23);
insert into t_stage (name,introduction,course_id,level) VALUES ('高性能Web平台','高性能Web平台',1,24);
insert into t_stage (name,introduction,course_id,level) VALUES ('分布式解决方案','分布式解决方案',1,25);
insert into t_stage (name,introduction,course_id,level) VALUES ('云原生实战','云原生实战',1,26);

insert into t_stage (name,introduction,course_id,level) VALUES ('Python 快速入门','Python快速入门',2,1);
insert into t_stage (name,introduction,course_id,level) VALUES ('Python 深入与提高','Python深入与提高',2,2);
insert into t_stage (name,introduction,course_id,level) VALUES ('Python 网络与并发编程','Python网络与并发编程',2,3);
insert into t_stage (name,introduction,course_id,level) VALUES ('函数式编程和核心特性','函数式编程和核心特性',2,4);
insert into t_stage (name,introduction,course_id,level) VALUES ('Linux 环境编程基础','Linux环境编程基础',2,5);
insert into t_stage (name,introduction,course_id,level) VALUES ('数据库编程基础','数据库编程基础',2,6);
insert into t_stage (name,introduction,course_id,level) VALUES ('网页编程基础','网页编程基础',2,7);
insert into t_stage (name,introduction,course_id,level) VALUES ('Flask框架','Flask框架',2,8);
insert into t_stage (name,introduction,course_id,level) VALUES ('Vue框架','Vue框架',2,9);
insert into t_stage (name,introduction,course_id,level) VALUES ('Flask百战电商后台项目','Flask百战电商后台项目',2,10);
insert into t_stage (name,introduction,course_id,level) VALUES ('Django框架','Django框架',2,11);
insert into t_stage (name,introduction,course_id,level) VALUES ('Python_大型电商项目','Python_大型电商项目',2,12);
insert into t_stage (name,introduction,course_id,level) VALUES ('Python_Tornado 框架','Python_Tornado 框架',2,13);
insert into t_stage (name,introduction,course_id,level) VALUES ('自动化操作办公软件、邮件、定时任务等','自动化操作办公软件、邮件、定时任务等',2,14);
insert into t_stage (name,introduction,course_id,level) VALUES ('Python 爬虫开发','Python爬虫开发',2,15);
insert into t_stage (name,introduction,course_id,level) VALUES ('算法与数据结构','算法与数据结构',2,16);


insert into t_stage (name,introduction,course_id,level) VALUES ('预职业规划/学习方法','预职业规划/学习方法',3,1);
insert into t_stage (name,introduction,course_id,level) VALUES ('HTML5+CSS3模块','HTML5+CSS3模块',3,2);
insert into t_stage (name,introduction,course_id,level) VALUES ('JavaScript编程模块','JavaScript编程模块',3,3);
insert into t_stage (name,introduction,course_id,level) VALUES ('jQuery编程模块','jQuery编程模块',3,4);
insert into t_stage (name,introduction,course_id,level) VALUES ('前后端交互','前后端交互',3,5);
insert into t_stage (name,introduction,course_id,level) VALUES ('音乐社区高级项目模块','音乐社区高级项目模块',3,6);
insert into t_stage (name,introduction,course_id,level) VALUES ('ECMAScript6新特性模块','ECMAScript6新特性模块',3,7);
insert into t_stage (name,introduction,course_id,level) VALUES ('JavaScript设计模式模块','JavaScript设计模式模块',3,8);
insert into t_stage (name,introduction,course_id,level) VALUES ('HTML5新特性模块','HTML5新特性模块',3,9);
insert into t_stage (name,introduction,course_id,level) VALUES ('Nodejs编程模块','Nodejs编程模块',3,10);
insert into t_stage (name,introduction,course_id,level) VALUES ('前端工程化','前端工程化',3,11);
insert into t_stage (name,introduction,course_id,level) VALUES ('数据可视化','数据可视化',3,12);
insert into t_stage (name,introduction,course_id,level) VALUES ('诱人的TypeScript','诱人的TypeScript',3,13);
insert into t_stage (name,introduction,course_id,level) VALUES ('微信小程序','微信小程序',3,14);
insert into t_stage (name,introduction,course_id,level) VALUES ('React知识体系','React知识体系',3,15);
insert into t_stage (name,introduction,course_id,level) VALUES ('React企业级项目','React企业级项目',3,16);
