insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) values ('Python 核心数据分析库——Pandas课程大升级！','Python 核心数据分析库——Pandas课程大升级！','|     章节     | 内容                             |
| :------------------: | :----------------------------------------------------------- |
| 章节2 Pandas基本使用 | 33：Pandas的介绍<br>34：Pandas数据结构_Series的使用<br/>35：Pandas数据结构_DataFrame的使用<br>36：Pandas读取数据_Excel文件<br>37：Pandas读取数据_CSV文件<br>38：Pandas读取数据_txt文件<br>39：Pandas读取数据_数据库数据<br>40：Pandas保存数据_外部文件<br>41：Pandas保存数据_数据库<br>42：快速了解数据<br>43：列的操作_修改列名<br>44：列的操作_获取列数据与删除列<br>45：列的操作_获取增加列数据<br>46：列的操作_获取增加列数据2<br>47：数据类型转_基本使用<br>48：索引操作_建立索引<br>49：索引操作_设置索引<br>50：索引操作_还原索引列<br>51：索引操作_索引的类型<br>52：索引操作_索引的修改<br/>53：索引操作_更新索引<br/>54：Series数据的获取<br/>55：DataFrame数据的获取<br/>56：isin方法的使用<br/>57：query方法的使用<br/>58：数据排序_索引<br/>59：数据排序_数据值<br/>60：修改数据值_指定的值<br/>61：修改数据值_批量修改值<br/>62：虚拟变量的创建<br/>63：变量值的分箱<br/>64：变量值的分组<br/>65：分组数据的汇总<br/>66：数据长宽格式的转换<br/>67：数据的合并<br/>68：数据的拼接<br/>69：了解缺失值<br/>70：填充缺失值<br/>71：删除缺失值<br/>72：删除重复的数据<br/>73：日期时间类型<br/>74：时间类型的转换<br/>75：时间索引的使用<br/>76：时间序列的使用<br/>77：数据的特征探索<br/>78：数据的探索_透视表<br/>79：数据的探索_交叉表<br/>80：图表的基本使用<br/>81：折线图与区域图<br/>82：条形图的使用<br/>83：直方图的使用<br/>84：饼图的使用<br/>85：箱图的使用<br/>86：散点图的使用<br/>87：优化Pandas的说明<br/>88：查看效率的时间工具<br/>89：处理大数据文件的方案<br/>90：代码优化_避免循环<br/>91：eval函数的使用 |',1,1,'2030-08-01 00:00:00',1);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) values ('强大的ShellScript脚本编程课程升级啦','强大的ShellScript脚本编程课程升级啦','',1,2,'2030-09-02 00:00:00',1);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('AIGC课程之Stable Diffusion（自选模型）AI绘图火爆上线','AIGC课程之Stable Diffusion（自选模型）AI绘图火爆上线','',1,3,'2030-09-03 00:00:00',1);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('炫酷的Midjourney图像AI绘图课程发布','炫酷的Midjourney图像AI绘图课程发布','',1,4,'2030-09-04 00:00:00',0);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('还没有用上ChatGPT吗？ChatGPT全攻略课程上线，速来！','还没有用上ChatGPT吗？ChatGPT全攻略课程上线，速来！','',1,5,'2030-09-05 00:00:00',1);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('Python项目又双叒升级，轻松实现本地音乐盒','Python项目又双叒升级，轻松实现本地音乐盒','',1,6,'2030-09-06 00:00:00',0);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('又炫又酷又炸的数据可视化前端课程更新','又炫又酷又炸的数据可视化前端课程更新','',1,7,'2030-09-07 00:00:00',1);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('Python：Linux 环境编程基础视频教程更新','Python：Linux 环境编程基础视频教程更新','',1,8,'2030-09-08 00:00:00',0);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('大厂必问面试题详解新增阿里、华为、百度面试题！','大厂必问面试题详解新增阿里、华为、百度面试题！','',1,9,'2030-09-09 00:00:00',0);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('2023版Spring 6框架教程，从入门到精通，学一次用十年','2023版Spring 6框架教程，从入门到精通，学一次用十年','',1,10,'2030-09-10 00:00:00',0);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('Python数据分析中必学的数学知识视频教程发布','Python数据分析中必学的数学知识视频教程发布','',1,11,'2030-09-11 00:00:00',0);
insert into t_update_course (name,introduction,info,course_id,stage_id,create_time,update_type) VALUES ('持续输出|大厂必问Java面试题详解视频教程更新','持续输出|大厂必问Java面试题详解视频教程更新','',1,12,'2030-09-12 00:00:00',1);
