# Generated by Django 4.2.3 on 2026-09-28 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0005_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='更新的课程标题')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='介绍')),
                ('info', models.TextField(blank=True, null=True, verbose_name='课程信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_type', models.IntegerField(blank=True, choices=[(0, '升级'), (1, '新增')], null=True, verbose_name='更新类型')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_app.course', verbose_name='课程分类')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_app.stage', verbose_name='阶段')),
            ],
            options={
                'db_table': 't_update_course',
            },
        ),
    ]
